const status_codes = {
    SUCCESS_CODE: 200,
    CREATED_CODE: 201,
    NO_CONTENT_CODE: 204,
    BAD_REQUEST_CODE: 400,
    UNAUTHORIZED_CODE: 401,
    FORBIDDEN_CODE: 403,
    WRONG_METHOD: 405,
    NOT_FOUND_CODE: 404,
    CONFLICT_CODE: 409,
    GONE_CODE: 410,
    UNSUPPORTED_MEDIA_TYPE_CODE: 415,
    VALIDATION_ERROR_CODE: 422,
    SERVICE_UNAVAILABLE_CODE: 503,
}

module.exports = status_codes;